### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by piecrustyumyum** [websitenmaker12/Advanced-Genetics#145] opened 2014-11-16 18:17 UTC
[13:13:06] [Server thread/ERROR]: Detected ongoing potential memory leak. 400 packets have leaked. Top offenders
[13:13:06] [Server thread/ERROR]:    AdvGen_Network : 218
[13:13:06] [Server thread/ERROR]:    FML : 108
[13:13:06] [Server thread/ERROR]:    CFM : 74

**Comment by piecrustyumyum** [comment] 2014-11-16 18:18
Nothing else is popping up for details on this, only that, outta nowhere.
I'm using the latest version of 1.7.10 Advanced Genetics which is Advanced genetics version 1.5.7 for minecraft 1.7.10

**Comment by LemADEC** [comment] 2014-11-21 09:03
Looks like a faulty implementation of network stack.
Is it frequent? what other mods/version do you have?
Can you reproduce with only AdvGenetics?

**Comment by websitenmaker12** [comment] 2014-11-21 11:24
I don't know what you have done with Advanced Genetics but it is possible that 218 get send to the client.

**Comment by mattymaats** [comment] 2014-11-27 11:36
I've seen this pop on our console a few times as well with AdvGen_Network being the top offender, running the hermitcraft modsauce pack.

**Comment by websitenmaker12** [comment] 2014-12-11 09:56
One of the background techniques of Advanceds Genetics is to send a packet for every entity that have a modified DNA. So if you have a lot of players that have a modified DNA, AG has to send a packet to every client when another player joins or adds/removes a gene from his DNA. That can causes some leaks when you a lot of players are playing. You many do you have?

**Comment by mattymaats** [comment] 2014-12-20 15:18
We generally have 30-/+ at peak times so it's not like it's a huge amount of players and last night I'm pretty sure I noticed 2000ish packets leaked with 99.9% being from AdvGen.

**Comment by tim-oster** [comment] 2015-03-03 15:39
Should be fixed in the next update.

**Closed as completed by tim-oster** 2015-03-03 15:39 UTC
